FONT_SIZE = 14
FONT_SIZE_SMALL = 12

FONT_NAME = 'DejaVuSans'


PAGE_TITLE_Y = 800
PAGE_TITLE_X = 50
PAGE_TITLE_FONT_SIZE = 24

PAGE_INGREDIENT_Y = 750
PAGE_INGREDIENT_X = 50
PAGE_INGREDIENT_FONT_SIZE = 12

PAGE_INGREDIENT_Y_STEP = 20

PAGE_MARGIN = 50

FIELD_LENGTH = 100
COLOR_LENGTH = 7
MEASUREMENT_UNIT_LENGTH = 20

VALIDATOR_MIN_VALUE = 1
VALIDATOR_MAX_VALUE = 32000
DEFAULT_VALUE = 0
